# Generated by Django 3.0.8 on 2020-07-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_main', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_name',
        ),
    ]
