# Generated by Django 3.0.8 on 2020-08-10 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_main', '0004_auto_20200808_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like_list',
            field=models.ManyToManyField(related_name='users_comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='post_like_list',
            field=models.ManyToManyField(related_name='users_post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
